name: Run Private Scripts and Deploy to Public Repo

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # ۱. کلون ریپازیتوری خصوصی در مسیر private_repo
      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          repository: F0rc3Run/all-sub-scrapper
          token: ${{ secrets.PAT }}
          path: private_repo

      # ۲. نصب پایتون
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ۳. نصب dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r private_repo/requirements.txt

      # ۴. اجرای اسکریپت اصلی
      - name: Run Main Script
        run: python private_repo/main.py

      # ۵. کلون ریپازیتوری عمومی مقصد
      - name: Clone Public Repo
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/F0rc3Run/F0rc3Run.git public_repo

      # ۶. کپی خروجی به مسیر مشخص
      - name: Copy Output
        run: |
          mkdir -p public_repo/splitted-by-protocol
          cp -r private_repo/output/* public_repo/splitted-by-protocol/

      # ۷. Push تغییرات
      - name: Commit and Push
        run: |
          cd public_repo
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add splitted-by-protocol/
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "bot: auto-update configs in 'splitted-by-protocol'"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/F0rc3Run/F0rc3Run.git HEAD:main
