name: Update README Stats

on:
  workflow_run:
    workflows: ["Check Proxies and Publish to FVL-S"]
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📊 Run Stats Generator
        run: python generate_stats.py

      - name: ✨ Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git add summary.md
          if ! git diff --staged --quiet; then
            git commit -m "Update README stats and summary"
            git push
          else
            echo "No changes to README.md."
          fi
