name: Generate and Push Proxy Data

on:
  schedule:
    - cron: '0 */6 * * *'  # هر ۶ ساعت
  workflow_dispatch:

jobs:
  push-to-public:
    runs-on: ubuntu-latest

    steps:
      - name: Clone private repo (Server-sort-by-country-to-pub)
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/F0rc3Run/Server-sort-by-country-to-pub.git private-repo

      - name: Install PHP
        run: sudo apt update && sudo apt install php -y

      - name: Run generate.php
        working-directory: private-repo
        run: php generate.php

      - name: List generated files
        working-directory: private-repo
        run: ls -l splitted-by-country

      - name: Clone public repo (destination)
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/F0rc3Run/F0rc3Run.git public-repo

      - name: Copy generated files to public repo
        run: |
          rm -rf public-repo/splitted-by-country/*
          cp -r private-repo/splitted-by-country/* public-repo/splitted-by-country/

      - name: Commit and push to public repo
        working-directory: public-repo
        run: |
          git config user.name "F0rc3Run Bot"
          git config user.email "bot@f0rc3run.local"

          echo "Update at $(date -u)" >> splitted-by-country/commit.txt
          rm -f splitted-by-country/all.raw.txt
          git add splitted-by-country/
          git commit -m "Auto-update proxy list at $(date -u)" || echo "No changes to commit"
          git push origin main
