name: Run Private Scripts and Deploy Output

on:
  schedule:
    - cron: '0 */6 * * *'  # هر 6 ساعت یک بار
  workflow_dispatch:

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout ریپازیتوری عمومی (خود workflow)
      - name: Checkout public repo
        uses: actions/checkout@v4

      # 2. کلون ریپازیتوری خصوصی
      - name: Checkout private repo
        run: |
          git clone https://x-access-token:${{ secrets.PRIVATE_REPO_PAT }}@github.com/F0rc3Run/all-sub-scrapper.git private_repo

      # 3. نصب پایتون
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 4. نصب وابستگی‌ها
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r private_repo/requirements.txt

      # 5. اجرای اسکریپت اصلی
      - name: Run main script
        run: python private_repo/main.py

      # 6. کپی خروجی به پوشه مورد نظر در ریپازیتوری عمومی
      - name: Copy output to public repo
        run: |
          DEST_FOLDER="splitted-by-protocol"
          mkdir -p $DEST_FOLDER
          cp -r private_repo/output/* $DEST_FOLDER/

      # 7. کامیت و پوش تغییرات
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $DEST_FOLDER/
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "bot: update output from private repo"
          git push
